sudo: required
dist: trusty
group: stable
language: node_js
node_js:
- '8'

cache:
  yarn: true
  directories:
     - ./node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

script:
  - yarn test

#after_success:
#  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
